export const NAME = 'user';

export const USER_REQUESTED = `${NAME}/USER_REQUESTED`;
export const USER_FULFILLED = `${NAME}/USER_FULFILLED`;

export const USER_ORDERS_REQUESTED = `${NAME}/USER_ORDERS_REQUESTED`;
export const USER_ORDERS_FULFILLED = `${NAME}/USER_ORDERS_FULFILLED`;
